<a href="https://colab.research.google.com/github/aldojda/MultivariateStatistics/blob/main/MEM_Tarea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Maestria en Ciencia de Datos

# Tarea 2

## Aldo Daniel Ojeda Rodriguez


**Instrucciones:** Contesta cada uno de los ejercicios en un archivo en Word o en hojas blancas. 
Puedes usar R, Excel o algún otro software, favor de anexar el código o el archivo de Excel. 
Al finalizar sube tus evidencias en el lugar correspondiente en Teams.

**1.-** Considera las siguientes matrices de covarianzas de un vector aleatorio X. Obtener la 
matriz de coeficiente de correlaciones para cada caso. Después, interpreta los valores 
obtenidos.

$$\begin{equation}
A = 
\left[
\begin{matrix}
4 & 3 & -2\\
3 & 6 & 2\\
-2 & 2 & 5
\end{matrix}
\right], B =
\left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right],
\end{equation}$$

la matriz de correlacion se puede definir como:

$$
\begin{equation}
\rho = (V^{1/2})^{-1}\Sigma (V^{1/2})^{-1}
\end{equation}
$$


In [12]:
import numpy as np
def ejercicio_1A():
    #Resultado 1
    #declaramos A
    A= np.matrix([[4,3,-2],[3,6,2],[-2,2,5]])
    #obtenemos la matriz v1/2
    V_1_2 = np.sqrt(np.eye(3)*np.diag(A))
    V_1_2inv = np.linalg.inv(V_1_2)
    #Multiplicamos matrices
    print('Ejercicio 1a')
    print('Resultado :')
    return np.dot(np.dot(V_1_2inv,A), V_1_2inv)  
ejercicio_1A()

Ejercicio 1a
Resultado :


matrix([[ 1.        ,  0.61237244, -0.4472136 ],
        [ 0.61237244,  1.        ,  0.36514837],
        [-0.4472136 ,  0.36514837,  1.        ]])

deacuredo al resultado anterior podemos ver que la correlación entre las variables **X1, X2** es de **0.61** lo cual indica una relación positiva moderada entre ambas variables, por otro lado podemos ver que la correlación entre las variables **X1, X3** es de **-0.44** lo cual indica una correlación negativa moderada y por otro lado tenemos la relación de las variables **X2, X3** siendo su correlación de **0.36** positiva moderada.

In [13]:
def ejercicio_1B():
    #Resultado 1
    #declaramos A
    B = np.matrix([[10, -3, -1, 5],[-3, 8, 3, 0],[-1, 3, 15, 1],[5, 0, 1, 4]])
    #obtenemos la matriz v1/2
    V_1_2 = np.sqrt(np.eye(4)*np.diag(B))
    V_1_2inv = np.linalg.inv(V_1_2)
    #Multiplicamos matrices
    #-------------------------
    print('Ejercicio 1b')
    print('Resultado :')
    #-------------------------
    return V_1_2inv * B * V_1_2inv  
ejercicio_1B()

Ejercicio 1b
Resultado :


matrix([[ 1.        , -0.3354102 , -0.08164966,  0.79056942],
        [-0.3354102 ,  1.        ,  0.27386128,  0.        ],
        [-0.08164966,  0.27386128,  1.        ,  0.12909944],
        [ 0.79056942,  0.        ,  0.12909944,  1.        ]])

en la matriz anterior podemos observar lo siguiente: 

    * El grupo de valor -0.33 muestra una relación negativa moderada (débil)
    * Los valores de la matriz cercanos a cero -0.08 y  0 no muestran relación
    * Los grupos de **0.12 y 0.27** muestran una relación positiva moderada
    * El grupo de correlación de 0.79 muestra una relación positiva fuerte 

**2.-** Para las matrices del problema 1, obtener  $V^{1/2}$ , $V^{-1/2}$  y verificar que  $ \rho = V^{-1/2} \Sigma V^{-1/2}$ y $ \Sigma = V^{1/2}\rho V^{1/2} $

Del problema 1A podemos obtener los valores $V^{1/2}$ , $V^{-1/2}$ siendo los siguientes:


$$
\begin{equation}
V^{1/2} = 
\left[
\begin{matrix}
\sqrt{2} & 0 & 0\\
0 & \sqrt{6} & 0\\
0 & 0 & \sqrt{5}
\end{matrix}
\right],  V^{-1/2} = 
\left[
\begin{matrix}
1 / \sqrt{2} & 0 & 0\\
0 & 1 /\sqrt{6} & 0\\
0 & 0 & 1 /\sqrt{5}
\end{matrix}
\right]
\end{equation}$$

Operando estas matrices con la matriz del problema 1A tenermos que los valores de $\rho$ y $\Sigma$ son los siguientes:


In [14]:
v_sqrt_ = np.sqrt(np.matrix([[1/4,0,0], [0,1/6,0],  [0,0, 1/5]]))
sigma = np.matrix([[4.0,3.0,-2.0],[3.0,6.0,2.0],[-2.0,2.0,5.0]])
#multiplicamos las matrices
rho = v_sqrt_ * sigma * v_sqrt_ 
rho

matrix([[ 1.        ,  0.61237244, -0.4472136 ],
        [ 0.61237244,  1.        ,  0.36514837],
        [-0.4472136 ,  0.36514837,  1.        ]])

In [15]:
v_sqrt_ = np.sqrt(np.matrix([[4,0,0], [0,6,0],  [0,0, 5]]))
#multiplicamos las matrices
sigma = v_sqrt_* rho * v_sqrt_
sigma

matrix([[ 4.,  3., -2.],
        [ 3.,  6.,  2.],
        [-2.,  2.,  5.]])

en los bloques de código anterior podemos observar que las ecuaciones si se cumplen como se espera.

Del problema 1B podemos obtener los valores $V^{1/2}$ , $V^{-1/2}$ siendo los siguientes:


$$
\begin{equation}
V^{1/2} = 
\left[
\begin{matrix}
\sqrt{10} & 0 & 0 & 0\\
0 & \sqrt{8} & 0 & 0\\
0 & 0 & \sqrt{15} & 0\\
0 & 0 & 0 & \sqrt{4}
\end{matrix}
\right],  V^{-1/2} = 
\left[
\begin{matrix}
1/\sqrt{10} & 0 & 0 & 0\\
0 & 1/\sqrt{8} & 0  & 0\\
0 & 0 & 1/\sqrt{15} & 0\\
0 & 0 & 0 & 1/\sqrt{4}
\end{matrix}
\right]
\end{equation}$$

Operando estas matrices con la matriz del problema 1A tenermos que los valores de $\rho$ y $\Sigma$ son los siguientes:

In [16]:
v_sqrt_ = np.sqrt(np.matrix([[1/10,0,0, 0], [0,1/8,0, 0],  [0,0, 1/15, 0], [0,0, 0, 1/4]]))
sigma = np.matrix([[10, -3, -1, 5],[-3, 8, 3, 0],[-1, 3, 15, 1],[5, 0, 1, 4]])
#multiplicamos las matrices
rho = v_sqrt_ * sigma * v_sqrt_ 
rho

matrix([[ 1.        , -0.3354102 , -0.08164966,  0.79056942],
        [-0.3354102 ,  1.        ,  0.27386128,  0.        ],
        [-0.08164966,  0.27386128,  1.        ,  0.12909944],
        [ 0.79056942,  0.        ,  0.12909944,  1.        ]])

In [17]:
v_sqrt_ = np.sqrt(np.matrix([[10,0,0, 0], [0,8,0, 0],  [0,0, 15, 0], [0,0, 0, 4]]))
#multiplicamos las matrices
sigma = v_sqrt_ * rho * v_sqrt_ 
sigma

matrix([[10., -3., -1.,  5.],
        [-3.,  8.,  3.,  0.],
        [-1.,  3., 15.,  1.],
        [ 5.,  0.,  1.,  4.]])

 como hemos observado al operar estos resultados podemos volver a generar los valores de $\rho$ Y $\Sigma$.

**3.-** Considera que : 

$$\begin{equation}
 \Sigma  =
\left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right],
\end{equation}$$

Obtener: 

A)  $Cov ~ (2X_1, - 4X_2)$.


$$Cov ~ (aX_1, bX_2) = ab\sigma_{1,2}$$
 
por lo tanto: 

$$Cov ~ (2X_1, - 4X_2) = 2 \cdot -4 \cdot \sigma_{1,2}$$

de la matriz $\Sigma$ tenemos que  $\sigma_{1,2} = -3$,  aplicandolo a la ecuación anterior tenemos que : 

$$Cov ~ (aX_1, bX_2) =  2 \cdot -4 \cdot -3 = 24 $$


In [18]:
#calculo de covarianza
sigma = np.matrix([[10.0, -3.0, -1.0, 5.0], [-3.0, 8.0, 3.0, 0.0], [-1.0, 3.0, 15.0, 1], [5.0, 0, 1.0, 4.0]])
c = np.matrix([[2, 0, 0, 0], [0, -4.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0], [0.0, 0, 0.0, 0.0]])
c* sigma* c.T

matrix([[ 40.,  24.,   0.,   0.],
        [ 24., 128.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])

B ) $Var ~ (3X_2-2X_3)$

Deacuerdo a las propiedades de la varianza tenemos:

$$\begin{equation} Var ~ (aX_1+ bX_2)  = Var ~ (\textbf{c'X}) = \textbf{c'}
\Sigma \textbf{c}
\end{equation}$$

siendo

$$\begin{equation}
 c  =
\left[
\begin{matrix}
 0\\
3 \\
-2\\
0 \\
\end{matrix}
\right]
\end{equation}$$

operando **c** y $\Sigma$ tenemos


$$\begin{equation} 
Var ~ (3X_2-2X_3) = 
\left[
\begin{matrix}
 0 & 3 & -2 & 0 
\end{matrix}
\right] \left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right] \left[
\begin{matrix}
 0\\
3 \\
-2\\
0 \\
\end{matrix}
\right] = 96
\end{equation}$$


In [19]:
sigma = np.matrix([[10.0, -3.0, -1.0, 5.0], [-3.0, 8.0, 3.0, 0.0], [-1.0, 3.0, 15.0, 1], [5.0, 0, 1.0, 4.0]])
c = np.matrix([0,3, -2, 0])
c* sigma* c.T

matrix([[96.]])

C ) $Var ~ (2X_1-4X_2+3X_3-X_4)$

Deacuerdo a las propiedades de la varianza tenemos:

$$\begin{equation} Var ~ (aX_1+ bX_2)  = Var ~ (\textbf{c'X}) = \textbf{c'}
\Sigma \textbf{c}
\end{equation}$$

siendo

$$\begin{equation}
 c  =
\left[
\begin{matrix}
 2\\
-4 \\
3\\
-1 \\
\end{matrix}
\right]
\end{equation}$$

operando **c** y $\Sigma$ tenemos


$$\begin{equation} 
Var ~ (3X_2-2X_3) = 
\left[
\begin{matrix}
 2 & -4 & 3 & -1 
\end{matrix}
\right] \left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right] \left[
\begin{matrix}
 2\\
-4 \\
3\\
-1 \\
\end{matrix}
\right] = 245
\end{equation}$$

In [20]:
sigma = np.matrix([[10.0, -3.0, -1.0, 5.0], [-3.0, 8.0, 3.0, 0.0], [-1.0, 3.0, 15.0, 1], [5.0, 0, 1.0, 4.0]])
c = np.matrix([2,-4, 3, -1])
c* sigma* c.T

matrix([[245.]])