<a href="https://colab.research.google.com/github/aldojda/MultivariateStatistics/blob/main/MEM_Tarea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Maestria en Ciencia de Datos

# Tarea 2

## Aldo Daniel Ojeda Rodriguez


**Instrucciones:** Contesta cada uno de los ejercicios en un archivo en Word o en hojas blancas. 
Puedes usar R, Excel o algún otro software, favor de anexar el código o el archivo de Excel. 
Al finalizar sube tus evidencias en el lugar correspondiente en Teams.

**1.-** Considera las siguientes matrices de covarianzas de un vector aleatorio X. Obtener la 
matriz de coeficiente de correlaciones para cada caso. Después, interpreta los valores 
obtenidos.

$$\begin{equation}
A = 
\left[
\begin{matrix}
4 & 3 & -2\\
3 & 6 & 2\\
-2 & 2 & 5
\end{matrix}
\right],~ B =
\left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right],
\end{equation}$$

la matriz de correlacion se puede definir como:

$$
\begin{equation}
\rho = (V^{1/2})^{-1}\Sigma (V^{1/2})^{-1}
\end{equation}
$$


In [30]:
import numpy as np
def ejercicio_1A():
    #Resultado 1
    #declaramos A
    A= np.matrix([[4,3,-2],[3,6,2],[-2,2,5]])
    #obtenemos la matriz v1/2
    V_1_2 = np.sqrt(np.eye(3)*np.diag(A))
    V_1_2inv = np.linalg.inv(V_1_2)
    #Multiplicamos matrices
    print('Ejercicio 1a')
    print('Resultado :')
    return np.dot(np.dot(V_1_2inv,A), V_1_2inv)  
ejercicio_1A()

Ejercicio 1a
Resultado :


matrix([[ 1.        ,  0.61237244, -0.4472136 ],
        [ 0.61237244,  1.        ,  0.36514837],
        [-0.4472136 ,  0.36514837,  1.        ]])

deacuredo al resultado anterior podemos ver que la correlación entre las variables **X1, X2** es de **0.61** lo cual indica una relación positiva moderada entre ambas variables, por otro lado podemos ver que la correlación entre las variables **X1, X3** es de **-0.44** lo cual indica una correlación negativa moderada y por otro lado tenemos la relación de las variables **X2, X3** siendo su correlación de **0.36** positiva moderada.

In [31]:
def ejercicio_1B():
    #Resultado 1
    #declaramos A
    B = np.matrix([[10, -3, -1, 5],[-3, 8, 3, 0],[-1, 3, 15, 1],[5, 0, 1, 4]])
    #obtenemos la matriz v1/2
    V_1_2 = np.sqrt(np.eye(4)*np.diag(B))
    V_1_2inv = np.linalg.inv(V_1_2)
    #Multiplicamos matrices
    #-------------------------
    print('Ejercicio 1b')
    print('Resultado :')
    #-------------------------
    return V_1_2inv * B * V_1_2inv  
ejercicio_1B()

Ejercicio 1b
Resultado :


matrix([[ 1.        , -0.3354102 , -0.08164966,  0.79056942],
        [-0.3354102 ,  1.        ,  0.27386128,  0.        ],
        [-0.08164966,  0.27386128,  1.        ,  0.12909944],
        [ 0.79056942,  0.        ,  0.12909944,  1.        ]])

en la matriz anterior podemos observar lo siguiente: 

    * El grupo de valor -0.33 muestra una relación negativa moderada (débil)
    * Los valores de la matriz cercanos a cero -0.08 y  0 no muestran relación
    * Los grupos de **0.12 y 0.27** muestran una relación positiva moderada
    * El grupo de correlación de 0.79 muestra una relación positiva fuerte 

**2.-** Para las matrices del problema 1, obtener  $V^{1/2}$ , $V^{-1/2}$  y verificar que  $ \rho = V^{-1/2} \Sigma V^{-1/2}$ y $ \Sigma = V^{1/2}\rho V^{1/2} $

Del problema 1A podemos obtener los valores $V^{1/2}$ , $V^{-1/2}$ siendo los siguientes:


$$
\begin{equation}
V^{1/2} = 
\left[
\begin{matrix}
\sqrt{2} & 0 & 0\\
0 & \sqrt{6} & 0\\
0 & 0 & \sqrt{5}
\end{matrix}
\right],  V^{-1/2} = 
\left[
\begin{matrix}
1 / \sqrt{2} & 0 & 0\\
0 & 1 /\sqrt{6} & 0\\
0 & 0 & 1 /\sqrt{5}
\end{matrix}
\right]
\end{equation}$$

Operando estas matrices con la matriz del problema 1A tenermos que los valores de $\rho$ y $\Sigma$ son los siguientes:


In [32]:
v_sqrt_ = np.sqrt(np.matrix([[1/4,0,0], [0,1/6,0],  [0,0, 1/5]]))
sigma = np.matrix([[4.0,3.0,-2.0],[3.0,6.0,2.0],[-2.0,2.0,5.0]])
#multiplicamos las matrices
rho = v_sqrt_ * sigma * v_sqrt_ 
rho

matrix([[ 1.        ,  0.61237244, -0.4472136 ],
        [ 0.61237244,  1.        ,  0.36514837],
        [-0.4472136 ,  0.36514837,  1.        ]])

In [33]:
v_sqrt_ = np.sqrt(np.matrix([[4,0,0], [0,6,0],  [0,0, 5]]))
#multiplicamos las matrices
sigma = v_sqrt_* rho * v_sqrt_
sigma

matrix([[ 4.,  3., -2.],
        [ 3.,  6.,  2.],
        [-2.,  2.,  5.]])

en los bloques de código anterior podemos observar que las ecuaciones si se cumplen como se espera.

Del problema 1B podemos obtener los valores $V^{1/2}$ , $V^{-1/2}$ siendo los siguientes:


$$
\begin{equation}
V^{1/2} = 
\left[
\begin{matrix}
\sqrt{10} & 0 & 0 & 0\\
0 & \sqrt{8} & 0 & 0\\
0 & 0 & \sqrt{15} & 0\\
0 & 0 & 0 & \sqrt{4}
\end{matrix}
\right],  V^{-1/2} = 
\left[
\begin{matrix}
1/\sqrt{10} & 0 & 0 & 0\\
0 & 1/\sqrt{8} & 0  & 0\\
0 & 0 & 1/\sqrt{15} & 0\\
0 & 0 & 0 & 1/\sqrt{4}
\end{matrix}
\right]
\end{equation}$$

Operando estas matrices con la matriz del problema 1A tenermos que los valores de $\rho$ y $\Sigma$ son los siguientes:

In [34]:
v_sqrt_ = np.sqrt(np.matrix([[1/10,0,0, 0], [0,1/8,0, 0],  [0,0, 1/15, 0], [0,0, 0, 1/4]]))
sigma = np.matrix([[10, -3, -1, 5],[-3, 8, 3, 0],[-1, 3, 15, 1],[5, 0, 1, 4]])
#multiplicamos las matrices
rho = v_sqrt_ * sigma * v_sqrt_ 
rho

matrix([[ 1.        , -0.3354102 , -0.08164966,  0.79056942],
        [-0.3354102 ,  1.        ,  0.27386128,  0.        ],
        [-0.08164966,  0.27386128,  1.        ,  0.12909944],
        [ 0.79056942,  0.        ,  0.12909944,  1.        ]])

In [35]:
v_sqrt_ = np.sqrt(np.matrix([[10,0,0, 0], [0,8,0, 0],  [0,0, 15, 0], [0,0, 0, 4]]))
#multiplicamos las matrices
sigma = v_sqrt_ * rho * v_sqrt_ 
sigma

matrix([[10., -3., -1.,  5.],
        [-3.,  8.,  3.,  0.],
        [-1.,  3., 15.,  1.],
        [ 5.,  0.,  1.,  4.]])

 como hemos observado al operar estos resultados podemos volver a generar los valores de $\rho$ Y $\Sigma$.

**3.-** Considera que : 

$$\begin{equation}
 \Sigma  =
\left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right],
\end{equation}$$

Obtener: 

A)  $Cov ~ (2X_1, - 4X_2)$.


$$Cov ~ (aX_1, bX_2) = ab\sigma_{1,2}$$
 
por lo tanto: 

$$Cov ~ (2X_1, - 4X_2) = 2 \cdot -4 \cdot \sigma_{1,2}$$

de la matriz $\Sigma$ tenemos que  $\sigma_{1,2} = -3$,  aplicandolo a la ecuación anterior tenemos que : 

$$Cov ~ (aX_1, bX_2) =  2 \cdot -4 \cdot -3 = 24 $$


In [36]:
#calculo de covarianza
sigma = np.matrix([[10.0, -3.0, -1.0, 5.0], [-3.0, 8.0, 3.0, 0.0], [-1.0, 3.0, 15.0, 1], [5.0, 0, 1.0, 4.0]])
c = np.matrix([[2, 0, 0, 0], [0, -4.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0], [0.0, 0, 0.0, 0.0]])
c* sigma* c.T

matrix([[ 40.,  24.,   0.,   0.],
        [ 24., 128.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])

B ) $Var ~ (3X_2-2X_3)$

Deacuerdo a las propiedades de la varianza tenemos:

$$\begin{equation} Var ~ (aX_1+ bX_2)  = Var ~ (\textbf{c'X}) = \textbf{c'}
\Sigma \textbf{c}
\end{equation}$$

siendo

$$\begin{equation}
 c  =
\left[
\begin{matrix}
 0\\
3 \\
-2\\
0 \\
\end{matrix}
\right]
\end{equation}$$

operando **c** y $\Sigma$ tenemos


$$\begin{equation} 
Var ~ (3X_2-2X_3) = 
\left[
\begin{matrix}
 0 & 3 & -2 & 0 
\end{matrix}
\right] \left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right] \left[
\begin{matrix}
 0\\
3 \\
-2\\
0 \\
\end{matrix}
\right] = 96
\end{equation}$$


In [37]:
sigma = np.matrix([[10.0, -3.0, -1.0, 5.0], [-3.0, 8.0, 3.0, 0.0], [-1.0, 3.0, 15.0, 1], [5.0, 0, 1.0, 4.0]])
c = np.matrix([0,3, -2, 0])
c* sigma* c.T

matrix([[96.]])

C ) $Var ~ (2X_1-4X_2+3X_3-X_4)$

Deacuerdo a las propiedades de la varianza tenemos:

$$\begin{equation} Var ~ (aX_1+ bX_2)  = Var ~ (\textbf{c'X}) = \textbf{c'}
\Sigma \textbf{c}
\end{equation}$$

siendo

$$\begin{equation}
 c  =
\left[
\begin{matrix}
 2\\
-4 \\
3\\
-1 \\
\end{matrix}
\right]
\end{equation}$$

operando **c** y $\Sigma$ tenemos


$$\begin{equation} 
Var ~ (3X_2-2X_3) = 
\left[
\begin{matrix}
 2 & -4 & 3 & -1 
\end{matrix}
\right] \left[
\begin{matrix}
10 & -3 & -1 & 5\\
-3 & 8 & 3 & 0\\
-1 & 3 & 15 & 1\\
5 & 0 & 1 & 4\\
\end{matrix}
\right] \left[
\begin{matrix}
 2\\
-4 \\
3\\
-1 \\
\end{matrix}
\right] = 245
\end{equation}$$

In [38]:
sigma = np.matrix([[10.0, -3.0, -1.0, 5.0], [-3.0, 8.0, 3.0, 0.0], [-1.0, 3.0, 15.0, 1], [5.0, 0, 1.0, 4.0]])
c = np.matrix([2,-4, 3, -1])
c* sigma* c.T

matrix([[245.]])

**4.-** Considera que : 

$$\begin{equation}
 \Sigma_X  =
\left[
\begin{matrix}
12 & 5 & 12\\
5 & 16 & 15\\
12 & 15 & 20\\
\end{matrix}
\right].
\end{equation}$$

Obtener la matriz de covarianzas del vector aleatorio Z donde:

A) $Z_1 = 3X_1 − 2X_2 + 5X_3$ ,  $Z_2 = 9X_1 + 6X_2 − 8X_3$ , $Z_3 = 4X_1 + X_2 − X_3$

obtenemos la matriz A:

$$\begin{equation}
 A  =
\left[
\begin{matrix}
3 & -2 & 5\\
9 & 6 & -8\\
4 & 1 & -1\\
\end{matrix}
\right].
\end{equation}$$

y operamos 
 $$Cov~(AX) = A \Sigma_X A' $$

In [39]:
sigma = np.matrix([[12,5, 12], [5,16, 15], [12,15,20]])
a = np.matrix([[3,-2, 5], [9,6, -8], [4,1,-1]])
a * sigma * a.T

matrix([[672, 274, 296],
        [274, 200, 151],
        [296, 151, 142]])

B) $Z_1 = 5X_1 − 2X_2 + 9X_3$
, $Z_2 = X_1 + X_2 − X_3$
, $Z_3 = 3X_1 + X_2 − 2X_3$
, $Z_4 = 4X_1 + X_2$

obtenemos la matriz B:

$$\begin{equation}
 B  =
\left[
\begin{matrix}
5 & -2 & 9\\
1 & 1 & -1\\
3 & 1 & -2\\
4 & 1 & 0\\
\end{matrix}
\right]
\end{equation}$$

In [40]:
sigma = np.matrix([[12,5, 12], [5,16, 15], [12,15,20]])
b = np.matrix([[5,-2, 9], [1, 1, -1], [3, 1, -2], [4, 1, 0]])
b * sigma * b.T

matrix([[2424,   76,  182,  760],
        [  76,    4,    7,   26],
        [ 182,    7,   30,   69],
        [ 760,   26,   69,  248]])

**5**. - Considera la matriz $Σ$ del problema 4. Obtener la distancia estadística (Mahalanobis) entre los dos puntos A, B dados. 

A) $A(3,−4,5)$ y $B(1,3,−2)$. 

Por definición tenemos que la distancia de Mahalonobis para dos vectores es: 


$$d(x, y) = \sqrt{(x-y)'\Sigma^{-1}(x-y)} $$ 

obtenemos la matriz $\Sigma^{-1}$ : 

$$\begin{equation}
 \Sigma^{-1}  =
\left[
\begin{matrix}
0.69 &  0.58 & -0.86\\
0.58 &  0.70 & -0.88\\
-0.86 & -0.88 & 1.22\\
\end{matrix}
\right].
\end{equation}$$

y operamos:

In [41]:
import numpy as np
sigma = np.matrix([[12,5, 12], [5,16, 15], [12,15,20]])
sigma_inv = np.linalg.inv(sigma)
a = np.matrix([3,-4,5]).T
b = np.matrix([1,3,-2]).T
np.sqrt((a-b).T * sigma_inv * (a-b))

matrix([[11.97761392]])


B) $A( 4,−8,9)$ y $B( 6,9,10)$.


In [42]:
import numpy as np
sigma = np.matrix([[12,5, 12], [5,16, 15], [12,15,20]])
sigma_inv = np.linalg.inv(sigma)
a = np.matrix([4,-8,9]).T
b = np.matrix([6,9,10]).T
np.sqrt((a-b).T * sigma_inv * (a-b))

matrix([[14.64857953]])

C) $A( 10,4,15)$ y el origen.



In [43]:
import numpy as np
sigma = np.matrix([[12,5, 12], [5,16, 15], [12,15,20]])
sigma_inv = np.linalg.inv(sigma)
a = np.matrix([10,4,15]).T
b = np.matrix([0,0,0]).T
np.sqrt((a-b).T * sigma_inv * (a-b))

matrix([[6.3656939]])

**6**.- Considera las matrices de covarianzas del problema 1. Para cada una obtener su varianza generalizada

podemos definir la varianza generalizada como el determinante de la matriz de covarianza
por lo tanto para la matriz A del problema 1 tenemos:



In [44]:
import numpy as np
A= np.matrix([[4.0,3.0,-2.0],[3.0,6.0,2.0],[-2.0,2.0,5.0]])
np.linalg.det(A).round(3)

11.0

y para la matriz B del problema 1 tenemos:

In [45]:
B = np.matrix([[10, -3, -1, 5],[-3, 8, 3, 0],[-1, 3, 15, 1],[5, 0, 1, 4]])
np.linalg.det(B).round(5)

1104.0

**7**.- Sea $X$ un vector aleatorio con distribución $N_5(μ, Σ)$, obtener:

A) $P\{(X-μ)'Σ^{-1}(X-μ)>3\}$

Sabamos que 

$$
(X-\mu)'Σ^{-1}(X-\mu) ≈ χ^2_p
$$

además sabemos que: 

$$X ≈ N_5(μ, Σ) ≈ d^2(X-μ)$$
por lo tanto la probabilidad 

$$P\{(X-μ)'Σ^{-1}(X-μ)>3\} = P\{d^2(X-μ > 3)\} = 1- χ^2.cdf(3,5) $$ 

In [46]:
from scipy.stats import chi2
1 - chi2.cdf(x = 3,df = 5, loc=0, scale=1)

0.6999858358786276

B) $~ P\{4<(X-μ)'Σ^{-1}(X-μ)< 6\}$

In [47]:
chi2.cdf(x = 6,df = 5, loc=0, scale=1) - chi2.cdf(x = 4,df = 5, loc=0, scale=1)

0.24319703293950146

C) $~ P\{(X-μ)'Σ^{-1}(X-μ)< 2\}$

In [48]:
chi2.cdf(x = 2,df = 5, loc=0, scale=1)

0.15085496391539038

C) Obtener el valor de $w$ tal que :   

$~ P\{(X-μ)'Σ^{-1}(X-μ)< w\} = 0.85$

In [49]:
chi2.ppf(q = 0.85 ,df = 5, loc=0, scale=1)

8.11519941305293


8.- Considera la muestra aleatoria de un vector aleatorio (datos en el ícono).
Obtener X y S. Interpreta los valores obtenidos.

In [50]:
#importamos google coolab para trabajar con archivos de Drive
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [51]:
import pandas as pd
df = pd.read_csv("gdrive/MyDrive/Maestría Ciencia de Datos/ Métodos Estadísticos Multivariados/datos_tarea2.csv")
df.head(2)

X1       X2       X3       X4       X5
0  91.165  106.549  146.410  313.598  509.574
1  94.264  120.121  155.148  321.554  500.530

obtenemos X

In [52]:
import numpy as np
df

X1       X2       X3       X4       X5
0    91.165  106.549  146.410  313.598  509.574
1    94.264  120.121  155.148  321.554  500.530
2    90.704  102.270  160.374  307.334  502.790
3    88.221   97.923  162.187  304.159  516.541
4    97.493  110.621  132.752  287.310  511.783
5   100.526  106.908  166.806  312.559  497.740
6   101.938  119.148  166.650  302.406  517.939
7    90.320   88.899  157.938  296.041  489.497
8    91.198  106.482  146.842  290.708  507.501
9    90.265   94.632  160.773  297.262  497.114
10   88.971   98.043  147.283  314.401  490.577
11   95.846  107.462  150.816  299.442  504.984
12   82.807   97.962  144.698  294.896  507.676
13   85.453   91.489  128.124  295.481  484.162
14   87.837   96.181  129.412  295.194  493.443
15   88.713  102.343  149.718  303.305  507.263
16   90.031   99.401  150.917  303.203  503.830
17   91.493  103.983  162.394  297.580  514.231
18   92.502  100.300  155.096  295.435  498.803
19   95.594  105.693  157.010  304.972  496.025
20  101.343  122.262  156.679  313.046  510.512
21   92.031   94.523  139.929  294.252  504.326
22   91.277  112.725  144.495  304.593  509.151
23   87.291   95.292  141.945  305.739  495.626
24   90.736  109.871  144.640  306.889  506.037
25   88.921  105.064  150.717  310.488  506.067
26   89.052  100.234  144.309  287.213  501.222
27   93.561  111.856  154.579  311.706  516.691
28   93.277  101.911  158.661  293.858  503.584
29   87.861   95.306  142.033  303.097  495.869
30   75.929   65.475  133.170  277.813  490.685
31   83.788   95.600  136.007  299.238  502.149
32   77.523   81.554  149.598  301.804  496.585
33   88.616  102.333  137.795  300.335  501.062
34   98.890  112.363  160.728  300.904  511.197
35   87.141   94.740  124.189  297.186  488.293
36   86.743   91.960  153.551  298.659  492.101
37   91.201  101.851  141.163  284.113  492.932
38   92.842  105.496  133.725  299.827  490.169
39   93.560  109.263  152.489  311.103  503.316
40   93.908  115.429  149.706  304.232  512.612
41   98.230  111.154  162.001  305.740  505.033
42   96.944  103.924  147.093  299.432  492.012
43   88.636  106.956  148.072  310.189  494.151
44   93.843   98.554  148.500  281.821  496.394
45   94.402  115.382  153.243  304.291  504.800
46   90.116   91.077  160.513  303.638  503.275
47   95.823  110.841  154.346  291.621  501.994
48   87.599   80.070  148.234  285.982  484.922
49   94.475   96.920  157.017  296.911  495.582

la matriz S seria por tanto:

In [53]:
df.cov()

X1          X2          X3         X4         X5
X1  27.088474   43.029097   26.502514  13.003355  17.403444
X2  43.029097  109.938370   35.671089  49.543822  53.919321
X3  26.502514   35.671089  103.328174  33.266840  36.491867
X4  13.003355   49.543822   33.266840  80.259596  22.005543
X5  17.403444   53.919321   36.491867  22.005543  70.952417